module

public import CrouzeixConjecture.Euclidean
public import Mathlib.Analysis.InnerProductSpace.Positive
public import Mathlib.Analysis.Matrix.Spectrum
public import Mathlib.Algebra.Polynomial.AlgebraMap
public import Mathlib.RingTheory.Adjoin.Basic

@[expose] public section

noncomputable section

open scoped ComplexOrder InnerProductSpace Matrix Matrix.Norms.L2Operator

namespace CrouzeixConjecture

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- Numerical range in the manuscript's convention: unit Euclidean vectors and `x^* A x`. -/
def numericalRange (A : SquareMatrix n) : Set ℂ :=
  {z | ∃ x : EuclideanVector n, ‖x‖ = 1 ∧ ⟪x, euclideanOperator A x⟫_ℂ = z}

/-- Positive dimension is explicit throughout the final result, so the numerical range is
nonempty. -/
theorem numericalRange_nonempty [Nonempty n] (A : SquareMatrix n) :
    (numericalRange A).Nonempty := by
  classical
  let i : n := Classical.choice (inferInstance : Nonempty n)
  let x : EuclideanVector n := EuclideanSpace.single i 1
  refine ⟨⟪x, euclideanOperator A x⟫_ℂ, x, ?_, rfl⟩
  simp [x]

/-- Polynomial evaluation at a matrix. -/
def polynomialEval (p : Polynomial ℂ) (A : SquareMatrix n) : SquareMatrix n :=
  Polynomial.aeval A p

/-- The matrix real part `(A + A^*) / 2`. -/
def rePart (A : SquareMatrix n) : SquareMatrix n :=
  (2 : ℂ)⁻¹ • (A + Aᴴ)

/-- Matrix positivity is positive semidefiniteness of the associated quadratic form. -/
def IsPositiveMatrix (A : SquareMatrix n) : Prop := A.PosSemidef

/-- Spectrum in the complex matrix algebra. -/
def matrixSpectrum (A : SquareMatrix n) : Set ℂ := spectrum ℂ A

/-- The unital complex algebra generated by one matrix. -/
def generatedAlgebra (A : SquareMatrix n) : Subalgebra ℂ (SquareMatrix n) :=
  Algebra.adjoin ℂ ({A} : Set (SquareMatrix n))

end CrouzeixConjecture
