module

public import CrouzeixConjecture.Definitions
public import Mathlib.Analysis.Convex.Integral
public import Mathlib.Analysis.Normed.Module.FiniteDimension
public import Mathlib.RingTheory.Adjoin.Polynomial.Basic
public import Mathlib.Topology.Algebra.InfiniteSum.Basic
public import Mathlib.Topology.Neighborhoods

@[expose] public section

noncomputable section

open MeasureTheory
open scoped Matrix.Norms.L2Operator

namespace CrouzeixConjecture

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- In finite dimensions, the unital algebra generated by a matrix is norm closed. -/
theorem isClosed_generatedAlgebra (A : SquareMatrix n) :
    IsClosed (generatedAlgebra A : Set (SquareMatrix n)) := by
  exact (generatedAlgebra A).toSubmodule.closed_of_finiteDimensional

/-- A norm-convergent net in the generated algebra has its limit in that algebra. -/
theorem generatedAlgebra_mem_of_tendsto {ι : Type*} {l : Filter ι} [l.NeBot]
    (A : SquareMatrix n) (f : ι → SquareMatrix n) (B : SquareMatrix n)
    (hf : Filter.Tendsto f l (nhds B)) (hmem : ∀ᶠ i in l, f i ∈ generatedAlgebra A) :
    B ∈ generatedAlgebra A := by
  exact (isClosed_generatedAlgebra A).mem_of_tendsto hf hmem

/-- A convergent matrix series whose terms lie in the generated algebra also has its sum there. -/
theorem generatedAlgebra_hasSum_mem {ι : Type*} (A : SquareMatrix n)
    (f : ι → SquareMatrix n) (B : SquareMatrix n) (hf : HasSum f B)
    (hmem : ∀ i, f i ∈ generatedAlgebra A) : B ∈ generatedAlgebra A := by
  apply (isClosed_generatedAlgebra A).mem_of_tendsto hf
  exact Filter.Eventually.of_forall fun s ↦
    (generatedAlgebra A).sum_mem fun i _ ↦ hmem i

/-- A Bochner integral of matrices that lie almost everywhere in a generated algebra remains in
that algebra.  Finite boundary measure is the only measure hypothesis needed in the manuscript's
companion-transform application. -/
theorem generatedAlgebra_integral_mem {ι : Type*} [MeasurableSpace ι]
    {mu : Measure ι} [IsFiniteMeasure mu]
    (A : SquareMatrix n) {f : ι → SquareMatrix n}
    (hf : Integrable f mu)
    (hmem : ∀ᵐ x ∂mu, f x ∈ generatedAlgebra A) :
    (∫ x, f x ∂mu) ∈ generatedAlgebra A := by
  by_cases hmu : mu = 0
  · subst mu
    simp
  · letI : NeZero mu := ⟨hmu⟩
    have hconvex : Convex ℝ (generatedAlgebra A : Set (SquareMatrix n)) := by
      simpa [Subalgebra.coe_toSubmodule] using
        ((generatedAlgebra A).toSubmodule.restrictScalars ℝ).convex
    have havg : (⨍ x, f x ∂mu) ∈ generatedAlgebra A :=
      hconvex.average_mem (isClosed_generatedAlgebra A) hmem hf
    have hscaledComplex :
        ((mu.real Set.univ : ℂ) • (⨍ x, f x ∂mu)) ∈ generatedAlgebra A :=
      (generatedAlgebra A).smul_mem havg (mu.real Set.univ : ℂ)
    have hscaledReal :
        (mu.real Set.univ : ℝ) • (⨍ x, f x ∂mu) ∈ generatedAlgebra A := by
      have heq :
          ((mu.real Set.univ : ℂ) • (⨍ x, f x ∂mu)) =
            (mu.real Set.univ : ℝ) • (⨍ x, f x ∂mu) := by
        ext a b
        simp [Complex.real_smul]
      rwa [← heq]
    simpa only [measure_smul_average] using hscaledReal

/-- Every element of the singly generated algebra is an evaluated complex polynomial. -/
theorem generatedAlgebra_mem_iff_exists_polynomial (A B : SquareMatrix n) :
    B ∈ generatedAlgebra A ↔ ∃ p : Polynomial ℂ, polynomialEval p A = B := by
  constructor
  · intro hB
    exact Algebra.adjoin_mem_exists_aeval (R := ℂ) (x := A) hB
  · rintro ⟨p, rfl⟩
    exact Polynomial.aeval_mem_adjoin_singleton ℂ A

/-- The generated algebra is exactly the range of polynomial evaluation. -/
theorem generatedAlgebra_eq_range_polynomialEval (A : SquareMatrix n) :
    (generatedAlgebra A : Set (SquareMatrix n)) = Set.range (fun p : Polynomial ℂ ↦
      polynomialEval p A) := by
  ext B
  constructor
  · intro hB
    exact (generatedAlgebra_mem_iff_exists_polynomial A B).mp hB
  · intro hB
    exact (generatedAlgebra_mem_iff_exists_polynomial A B).mpr hB

end CrouzeixConjecture
