module

public import CrouzeixConjecture.GeneratedAlgebra
public import CrouzeixConjecture.Spectrum
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.LinearAlgebra.Matrix.NonsingularInverse

@[expose] public section

noncomputable section

open scoped Matrix Matrix.Norms.L2Operator

namespace CrouzeixConjecture

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- A finite-dimensional matrix subalgebra is inverse-closed for elements that are units in
the ambient matrix algebra.  This supplies the algebra-membership step following
`eq:direct-completion`. -/
theorem matrix_inv_mem_subalgebra_of_mem_of_isUnit
    (A : Subalgebra ℂ (SquareMatrix n)) {x : SquareMatrix n}
    (hx : x ∈ A) (hunit : IsUnit x) : x⁻¹ ∈ A := by
  let xA : A := ⟨x, hx⟩
  let leftMul : A →ₗ[ℂ] A := LinearMap.mulLeft ℂ xA
  have hinjective : Function.Injective leftMul := by
    intro y z hyz
    apply Subtype.ext
    apply hunit.mul_left_cancel
    exact congrArg Subtype.val hyz
  have hsurjective : Function.Surjective leftMul :=
    LinearMap.surjective_of_injective hinjective
  obtain ⟨y, hy⟩ := hsurjective 1
  have hxy : x * y.val = 1 := by
    exact congrArg Subtype.val hy
  have hinverse : x⁻¹ = y.val := Matrix.inv_eq_right_inv hxy
  rw [hinverse]
  exact y.property

/-- Every resolvent outside the matrix spectrum belongs to the unital algebra generated by
the matrix.  This supplies the key algebra-membership input for contour-defined matrix
holomorphic functions. -/
theorem resolvent_mem_generatedAlgebra (B : SquareMatrix n) {sigma : ℂ}
    (hsigma : sigma ∉ matrixSpectrum B) :
    (sigma • (1 : SquareMatrix n) - B)⁻¹ ∈ generatedAlgebra B := by
  have hmem : sigma • (1 : SquareMatrix n) - B ∈ generatedAlgebra B := by
    exact (generatedAlgebra B).sub_mem
      ((generatedAlgebra B).smul_mem (generatedAlgebra B).one_mem sigma)
      (Algebra.subset_adjoin (Set.mem_singleton B))
  have hunit : IsUnit (sigma • (1 : SquareMatrix n) - B) := by
    have hunit' : IsUnit (algebraMap ℂ (SquareMatrix n) sigma - B) :=
      spectrum.notMem_iff.mp (show sigma ∉ spectrum ℂ B from hsigma)
    simpa only [Algebra.algebraMap_eq_smul_one] using hunit'
  exact matrix_inv_mem_subalgebra_of_mem_of_isUnit
    (generatedAlgebra B) hmem hunit

/-- A point outside any set containing the numerical range is a resolvent point whose inverse
belongs to the generated algebra. -/
theorem resolvent_mem_generatedAlgebra_of_numericalRange_subset
    (B : SquareMatrix n) {Omega : Set ℂ}
    (hWB : numericalRange B ⊆ Omega) {sigma : ℂ} (hsigma : sigma ∉ Omega) :
    (sigma • (1 : SquareMatrix n) - B)⁻¹ ∈ generatedAlgebra B := by
  apply resolvent_mem_generatedAlgebra B
  intro hspectral
  exact hsigma (hWB (matrixSpectrum_subset_numericalRange B hspectral))

end CrouzeixConjecture
