module

public import CrouzeixConjecture.ParametricBoundary

@[expose] public section

noncomputable section

open MeasureTheory
open scoped BoundedContinuousFunction ComplexConjugate ComplexOrder Matrix
  Matrix.Norms.L2Operator

namespace CrouzeixConjecture

variable {i n : Type*} [TopologicalSpace i] [CompactSpace i]
  [MeasurableSpace i] [OpensMeasurableSpace i]
  [Fintype n] [DecidableEq n] [Nonempty n]

/-- The positive boundary density obtained from the supported parametrization.  Its mass
identity is derived from the constant-polynomial instance of the Cauchy formula, rather than
stored as independent boundary data. -/
def parametricPositiveBoundaryDensity
    [IsFiniteMeasure (mu : Measure i)]
    (Gamma : ParametricConvexBoundary (i := i) Omega)
    (B : SquareMatrix n) (hWB : numericalRange B ⊆ Omega)
    (hCauchy : HasParametricPolynomialCauchyFormula Gamma mu B) :
    PositiveBoundaryDensity (n := n) mu where
  density := parametricDoubleLayerDensity Gamma B
  integrable_density := integrable_parametricDoubleLayerDensity Gamma B hWB
  posSemidef_ae := Filter.Eventually.of_forall
    (parametricDoubleLayerDensity_posSemidef Gamma B hWB)
  mass_eq_two_one := by
    have hfirst := integrable_parametricBoundaryFirstPart
      (mu := mu) Gamma B hWB
    have hadjoint : Integrable
        (fun x ↦ (parametricBoundaryFirstPart Gamma B x)ᴴ) mu :=
      integrable_of_continuous_compact
        (continuous_parametricBoundaryFirstPart Gamma B hWB).matrix_conjTranspose
    have hfirstMass :
        ∫ x, parametricBoundaryFirstPart Gamma B x ∂mu =
          (1 : SquareMatrix n) := by
      simpa [polynomialEval] using hCauchy (1 : Polynomial ℂ)
    rw [show (fun x ↦ parametricDoubleLayerDensity Gamma B x) =
        fun x ↦ parametricBoundaryFirstPart Gamma B x +
          (parametricBoundaryFirstPart Gamma B x)ᴴ by
      rfl]
    rw [integral_add hfirst hadjoint, ← conjTranspose_integral hfirst,
      hfirstMass, Matrix.conjTranspose_one]
    module

/-- The companion transform for an arbitrary bounded continuous boundary function. -/
def parametricBoundaryCompanion
    (Gamma : ParametricConvexBoundary (i := i) Omega)
    (mu : Measure i) (B : SquareMatrix n) (h : i →ᵇ ℂ) : SquareMatrix n :=
  ∫ x, star (h x) • parametricBoundaryFirstPart Gamma B x ∂mu

omit [Nonempty n] in
theorem integrable_parametricBoundaryCompanion
    [IsFiniteMeasure (mu : Measure i)]
    (Gamma : ParametricConvexBoundary (i := i) Omega)
    (B : SquareMatrix n) (hWB : numericalRange B ⊆ Omega) (h : i →ᵇ ℂ) :
    Integrable (fun x ↦ star (h x) • parametricBoundaryFirstPart Gamma B x) mu := by
  apply integrable_of_continuous_compact
  exact h.continuous.star.smul (continuous_parametricBoundaryFirstPart Gamma B hWB)

omit [Nonempty n] in
/-- The companion lies in the algebra generated by the auxiliary matrix. -/
theorem parametricBoundaryCompanion_mem_generatedAlgebra
    [IsFiniteMeasure (mu : Measure i)]
    (Gamma : ParametricConvexBoundary (i := i) Omega)
    (B : SquareMatrix n) (hWB : numericalRange B ⊆ Omega) (h : i →ᵇ ℂ) :
    parametricBoundaryCompanion Gamma mu B h ∈ generatedAlgebra B := by
  apply generatedAlgebra_integral_mem B
    (integrable_parametricBoundaryCompanion Gamma B hWB h)
  exact Filter.Eventually.of_forall fun x ↦ by
    have hres : parametricBoundaryResolvent Gamma B x ∈ generatedAlgebra B := by
      apply resolvent_mem_generatedAlgebra_of_numericalRange_subset B hWB
      exact (Gamma.supported x).sigma_not_mem
    have hnormal := (generatedAlgebra B).smul_mem hres (Gamma.normal x)
    have hfirst : parametricBoundaryFirstPart Gamma B x ∈ generatedAlgebra B := by
      exact ((generatedAlgebra B).toSubmodule.restrictScalars ℝ).smul_mem
        ((2 * Real.pi : ℝ)⁻¹ * Gamma.speed x) hnormal
    exact (generatedAlgebra B).smul_mem hfirst (star (h x))

omit [Nonempty n] in
/-- Generic double-layer identity: the analytic half is supplied by a Cauchy evaluation and the
second half is the adjoint of the companion. -/
theorem two_smul_boundaryPhi_parametric_eq
    [IsFiniteMeasure (mu : Measure i)]
    (Gamma : ParametricConvexBoundary (i := i) Omega)
    (B : SquareMatrix n) (hWB : numericalRange B ⊆ Omega)
    (hCauchy : HasParametricPolynomialCauchyFormula Gamma mu B)
    (h : i →ᵇ ℂ) (hB : SquareMatrix n)
    (hCauchyValue :
      ∫ x, h x • parametricBoundaryFirstPart Gamma B x ∂mu = hB) :
    (2 : ℂ) • boundaryPhiCLM
        (parametricPositiveBoundaryDensity Gamma B hWB hCauchy) h =
      hB + (parametricBoundaryCompanion Gamma mu B h)ᴴ := by
  let first : i → SquareMatrix n := parametricBoundaryFirstPart Gamma B
  have hfirst : Integrable (fun x ↦ h x • first x) mu := by
    apply integrable_of_continuous_compact
    exact h.continuous.smul (continuous_parametricBoundaryFirstPart Gamma B hWB)
  have hcompanion : Integrable (fun x ↦ star (h x) • first x) mu :=
    integrable_parametricBoundaryCompanion Gamma B hWB h
  have hsecond : Integrable (fun x ↦ h x • (first x)ᴴ) mu := by
    apply integrable_of_continuous_compact
    exact h.continuous.smul
      (continuous_parametricBoundaryFirstPart Gamma B hWB).matrix_conjTranspose
  have hsecondIntegral :
      ∫ x, h x • (first x)ᴴ ∂mu =
        (parametricBoundaryCompanion Gamma mu B h)ᴴ := by
    rw [parametricBoundaryCompanion, conjTranspose_integral hcompanion]
    apply integral_congr_ae
    exact Filter.Eventually.of_forall fun x ↦ by
      simp only [Matrix.conjTranspose_smul, star_star]
  rw [boundaryPhiCLM_apply, boundaryPhi]
  simp only [smul_smul]
  rw [show (2 : ℂ) * (2 : ℂ)⁻¹ = 1 by norm_num, one_smul]
  change (∫ x, h x • (first x + (first x)ᴴ) ∂mu) = _
  rw [show (fun x ↦ h x • (first x + (first x)ᴴ)) =
      fun x ↦ h x • first x + h x • (first x)ᴴ by
    funext x
    exact smul_add _ _ _]
  rw [integral_add hfirst hsecond, hCauchyValue, hsecondIntegral]

end CrouzeixConjecture
