module

public import CrouzeixConjecture.Definitions
public import Mathlib.RingTheory.Adjoin.Polynomial

@[expose] public section

noncomputable section

open scoped InnerProductSpace Matrix Matrix.Norms.L2Operator

namespace CrouzeixConjecture

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- Polynomial evaluation commutes with the star-algebra equivalence from matrices to
continuous operators on Euclidean space. -/
theorem euclideanOperator_polynomialEval (p : Polynomial ℂ) (A : SquareMatrix n) :
    euclideanOperator (polynomialEval p A) = Polynomial.aeval (euclideanOperator A) p := by
  exact (Polynomial.aeval_algHom_apply (euclideanOperator (n := n)) A p).symm

/-- The matrix spectrum is exactly the spectrum of the corresponding continuous operator. -/
theorem matrixSpectrum_eq_operatorSpectrum (A : SquareMatrix n) :
    matrixSpectrum A = spectrum ℂ (euclideanOperator A) := by
  exact (AlgEquiv.spectrum_eq (euclideanOperator (n := n)) A).symm

/-- Every spectral value of a finite complex matrix lies in its numerical range.

The normalization is explicit: a nonzero eigenvector `v` is replaced by
`(‖v‖ : ℂ)⁻¹ • v`.  No nonemptiness assumption on the index type is needed, since
membership in the spectrum itself supplies the nonzero eigenvector. -/
theorem matrixSpectrum_subset_numericalRange (A : SquareMatrix n) :
    matrixSpectrum A ⊆ numericalRange A := by
  intro z hz
  have hzLinear : z ∈ spectrum ℂ (Matrix.toLpLin 2 2 A) := by
    rw [Matrix.spectrum_toLpLin 2]
    simpa only [matrixSpectrum] using hz
  obtain ⟨v, hv⟩ :=
    (Module.End.HasEigenvalue.of_mem_spectrum hzLinear).exists_hasEigenvector
  let x : EuclideanVector n := (‖v‖ : ℂ)⁻¹ • v
  have hvNorm : ‖v‖ ≠ 0 := norm_ne_zero_iff.mpr hv.2
  have hxNorm : ‖x‖ = 1 := by
    simp [x, norm_smul, hvNorm]
  refine ⟨x, hxNorm, ?_⟩
  have hxEigen : euclideanOperator A x = z • x := by
    change Matrix.toLpLin 2 2 A x = z • x
    simp [x, hv.apply_eq_smul, smul_smul, mul_comm]
  rw [hxEigen, inner_smul_right, inner_self_eq_norm_sq_to_K, hxNorm]
  norm_num

/-- Every polynomial in `A` belongs to the unital complex algebra generated by `A`. -/
theorem polynomialEval_mem_generatedAlgebra (p : Polynomial ℂ) (A : SquareMatrix n) :
    polynomialEval p A ∈ generatedAlgebra A := by
  simpa only [polynomialEval, generatedAlgebra] using
    (Polynomial.aeval_mem_adjoin_singleton ℂ (p := p) A)

end CrouzeixConjecture
