-- GENERATED from the Crouzeix textbook contracts. DO NOT EDIT.

import CrouzeixTextbook.Part01.Chapter01
import CrouzeixTextbook.Part01.Chapter02
import CrouzeixTextbook.Part01.Chapter03
import CrouzeixTextbook.Part01.Chapter04
import CrouzeixTextbook.Part01.Chapter05
import CrouzeixTextbook.Part01.Chapter06
import CrouzeixTextbook.Part02.Chapter07
import CrouzeixTextbook.Part02.Chapter08
import CrouzeixTextbook.Part02.Chapter09
import CrouzeixTextbook.Part02.Chapter10
import CrouzeixTextbook.Part02.Chapter11
import CrouzeixTextbook.Part02.Chapter12
import CrouzeixTextbook.Part03.Chapter13
import CrouzeixTextbook.Part03.Chapter14
import CrouzeixTextbook.Part03.Chapter15
import CrouzeixTextbook.Part03.Chapter16
import CrouzeixTextbook.Part03.Chapter17
import CrouzeixTextbook.Part03.Chapter18
import CrouzeixTextbook.Part04.Chapter19
import CrouzeixTextbook.Part04.Chapter20
import CrouzeixTextbook.Part04.Chapter21
import CrouzeixTextbook.Part04.Chapter22
import CrouzeixTextbook.Part04.Chapter23
import CrouzeixTextbook.Part04.Chapter24
import CrouzeixTextbook.Part05.Chapter25
import CrouzeixTextbook.Part05.Chapter26
import CrouzeixTextbook.Part05.Chapter27
import CrouzeixTextbook.Part05.Chapter28
import CrouzeixTextbook.Part06.Chapter29
import CrouzeixTextbook.Part06.Chapter30
import CrouzeixTextbook.Part06.Chapter31
import CrouzeixTextbook.Part06.Chapter32
import CrouzeixTextbook.Part06.Chapter33
import CrouzeixTextbook.Part06.Chapter34
import CrouzeixTextbook.Part06.Chapter35

set_option linter.defProp false

#check CrouzeixConjecture.IsPositiveRealCompletion
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0001 :=
  @CrouzeixConjecture.IsPositiveRealCompletion
#check CrouzeixConjecture.LoristSchwenninger.DilationData.adjacentPowerDefect_factorization
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0002 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.adjacentPowerDefect_factorization
#check CrouzeixConjecture.LoristSchwenninger.DilationData.compressedAdjointPower_norm_le_one
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0003 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.compressedAdjointPower_norm_le_one
#check CrouzeixConjecture.LoristSchwenninger.DilationData.doubledCompressedAdjointPower_norm_le_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0004 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.doubledCompressedAdjointPower_norm_le_two
#check CrouzeixConjecture.LoristSchwenninger.DilationData.equation_three_lower_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0005 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.equation_three_lower_bound
#check CrouzeixConjecture.LoristSchwenninger.DilationData.norm_target_le_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0006 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.norm_target_le_two
#check CrouzeixConjecture.LoristSchwenninger.DilationData.perturbation_commutes_with_target
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0007 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.perturbation_commutes_with_target
#check CrouzeixConjecture.LoristSchwenninger.DilationData.recurrence_difference_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0008 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.recurrence_difference_identity
#check CrouzeixConjecture.LoristSchwenninger.DilationData.recurrence_difference_lower_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0009 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.recurrence_difference_lower_bound
#check CrouzeixConjecture.LoristSchwenninger.DilationData.target_power_norm_le_two_add_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0010 :=
  @CrouzeixConjecture.LoristSchwenninger.DilationData.target_power_norm_le_two_add_bound
#check CrouzeixConjecture.LoristSchwenninger.bcfMulL_norm_le_one
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0011 :=
  @CrouzeixConjecture.LoristSchwenninger.bcfMulL_norm_le_one
#check CrouzeixConjecture.LoristSchwenninger.bcfMulL_pow
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0012 :=
  @CrouzeixConjecture.LoristSchwenninger.bcfMulL_pow
#check CrouzeixConjecture.LoristSchwenninger.boundaryEmbedding_adjoint_comp_bcfMulL_comp_boundaryEmbedding
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0013 :=
  @CrouzeixConjecture.LoristSchwenninger.boundaryEmbedding_adjoint_comp_bcfMulL_comp_boundaryEmbedding
#check CrouzeixConjecture.LoristSchwenninger.boundaryEmbedding_adjoint_comp_bcfMulL_pow_comp_boundaryEmbedding
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0014 :=
  @CrouzeixConjecture.LoristSchwenninger.boundaryEmbedding_adjoint_comp_bcfMulL_pow_comp_boundaryEmbedding
#check CrouzeixConjecture.LoristSchwenninger.dilationDataOfParametricPolynomial
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0015 :=
  @CrouzeixConjecture.LoristSchwenninger.dilationDataOfParametricPolynomial
#check CrouzeixConjecture.LoristSchwenninger.norm_euclideanOperator_polynomialEval_le_two_of_parametricBoundary
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0016 :=
  @CrouzeixConjecture.LoristSchwenninger.norm_euclideanOperator_polynomialEval_le_two_of_parametricBoundary
#check CrouzeixConjecture.LoristSchwenninger.scalar_combined_inequality_of_recurrence_bounds
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0017 :=
  @CrouzeixConjecture.LoristSchwenninger.scalar_combined_inequality_of_recurrence_bounds
#check CrouzeixConjecture.LoristSchwenninger.scalar_endpoint_le_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0018 :=
  @CrouzeixConjecture.LoristSchwenninger.scalar_endpoint_le_two
#check CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_holomorphicMatrixEval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0019 :=
  @CrouzeixConjecture.PositivePeriodicRadialData.OrientedRadialConvexBoundary.parametricBoundaryIntegral_eq_holomorphicMatrixEval
#check CrouzeixConjecture.boundaryPhi_norm_le
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0020 :=
  @CrouzeixConjecture.boundaryPhi_norm_le
#check CrouzeixConjecture.boundaryPhi_one
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0021 :=
  @CrouzeixConjecture.boundaryPhi_one
#check CrouzeixConjecture.boundaryPhi_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0022 :=
  @CrouzeixConjecture.boundaryPhi_posSemidef
#check CrouzeixConjecture.boundaryPhi_star
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0023 :=
  @CrouzeixConjecture.boundaryPhi_star
#check CrouzeixConjecture.canonicalParallelOrientedRadialBoundaryStatement
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0024 :=
  @CrouzeixConjecture.canonicalParallelOrientedRadialBoundaryStatement
#check CrouzeixConjecture.closedOperatorNumericalRange_isCompact
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0025 :=
  @CrouzeixConjecture.closedOperatorNumericalRange_isCompact
#check CrouzeixConjecture.closedOperatorNumericalRange_nonempty
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0026 :=
  @CrouzeixConjecture.closedOperatorNumericalRange_nonempty
#check CrouzeixConjecture.completionCorrectionKernel_sampling_eq_zero
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0027 :=
  @CrouzeixConjecture.completionCorrectionKernel_sampling_eq_zero
#check CrouzeixConjecture.completionCorrectionKernel_sampling_quadratic_eq
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0028 :=
  @CrouzeixConjecture.completionCorrectionKernel_sampling_quadratic_eq
#check CrouzeixConjecture.completionDiagonalizableMatrix_euclideanOperator_norm_eq
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0029 :=
  @CrouzeixConjecture.completionDiagonalizableMatrix_euclideanOperator_norm_eq
#check CrouzeixConjecture.completionDiagonalizableMatrix_norm_eq_completionSimilarity_norm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0030 :=
  @CrouzeixConjecture.completionDiagonalizableMatrix_norm_eq_completionSimilarity_norm
#check CrouzeixConjecture.completionGramMatrix_isUnit
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0031 :=
  @CrouzeixConjecture.completionGramMatrix_isUnit
#check CrouzeixConjecture.completionGramMatrix_posDef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0032 :=
  @CrouzeixConjecture.completionGramMatrix_posDef
#check CrouzeixConjecture.completionGramMatrix_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0033 :=
  @CrouzeixConjecture.completionGramMatrix_posSemidef
#check CrouzeixConjecture.completionKernelModel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0034 :=
  @CrouzeixConjecture.completionKernelModel
#check CrouzeixConjecture.completionP_congruence_eq_gramian_four
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0035 :=
  @CrouzeixConjecture.completionP_congruence_eq_gramian_four
#check CrouzeixConjecture.completionPolarUnitary_mem_unitaryGroup
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0036 :=
  @CrouzeixConjecture.completionPolarUnitary_mem_unitaryGroup
#check CrouzeixConjecture.completionR_congruence_eq_gramian_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0037 :=
  @CrouzeixConjecture.completionR_congruence_eq_gramian_two
#check CrouzeixConjecture.completionResolventKernel_sampling_quadratic_eq
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0038 :=
  @CrouzeixConjecture.completionResolventKernel_sampling_quadratic_eq
#check CrouzeixConjecture.completionSquareRootData_of_isUnit
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0039 :=
  @CrouzeixConjecture.completionSquareRootData_of_isUnit
#check CrouzeixConjecture.completionX_congruence_eq_gramian_difference
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0040 :=
  @CrouzeixConjecture.completionX_congruence_eq_gramian_difference
#check CrouzeixConjecture.completion_X_inequality_of_positiveKernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0041 :=
  @CrouzeixConjecture.completion_X_inequality_of_positiveKernel
#check CrouzeixConjecture.complexAreaForm_I_mul_right
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0042 :=
  @CrouzeixConjecture.complexAreaForm_I_mul_right
#check CrouzeixConjecture.complexAreaForm_radialTangent_pos
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0043 :=
  @CrouzeixConjecture.complexAreaForm_radialTangent_pos
#check CrouzeixConjecture.contDiff_one_parallelRadialParameterPoint
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0044 :=
  @CrouzeixConjecture.contDiff_one_parallelRadialParameterPoint
#check CrouzeixConjecture.continuousOn_parametricBoundaryIntegral
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0045 :=
  @CrouzeixConjecture.continuousOn_parametricBoundaryIntegral
#check CrouzeixConjecture.convexProjection_variational
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0046 :=
  @CrouzeixConjecture.convexProjection_variational
#check CrouzeixConjecture.doubleLayerResolvent
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0047 :=
  @CrouzeixConjecture.doubleLayerResolvent
#check CrouzeixConjecture.doubleLayerResolvent_congruence_density
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0048 :=
  @CrouzeixConjecture.doubleLayerResolvent_congruence_density
#check CrouzeixConjecture.doubleLayerSupportMatrix_posSemidef_of_outwardBoundarySupport
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0049 :=
  @CrouzeixConjecture.doubleLayerSupportMatrix_posSemidef_of_outwardBoundarySupport
#check CrouzeixConjecture.euclideanOperator_conjTranspose
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0050 :=
  @CrouzeixConjecture.euclideanOperator_conjTranspose
#check CrouzeixConjecture.exists_hasDistinctEigenvalues_norm_sub_lt
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0051 :=
  @CrouzeixConjecture.exists_hasDistinctEigenvalues_norm_sub_lt
#check CrouzeixConjecture.exists_maxFunctionModulusOnSet
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0052 :=
  @CrouzeixConjecture.exists_maxFunctionModulusOnSet
#check CrouzeixConjecture.gramianTerm_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0053 :=
  @CrouzeixConjecture.gramianTerm_posSemidef
#check CrouzeixConjecture.gramian_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0054 :=
  @CrouzeixConjecture.gramian_posSemidef
#check CrouzeixConjecture.gramian_two_sub_gramian_four_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0055 :=
  @CrouzeixConjecture.gramian_two_sub_gramian_four_posSemidef
#check CrouzeixConjecture.holomorphicCrouzeixBound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0056 :=
  @CrouzeixConjecture.holomorphicCrouzeixBound
#check CrouzeixConjecture.holomorphicCrouzeixRationalBound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0057 :=
  @CrouzeixConjecture.holomorphicCrouzeixRationalBound
#check CrouzeixConjecture.holomorphicMatrixEval_add
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0058 :=
  @CrouzeixConjecture.holomorphicMatrixEval_add
#check CrouzeixConjecture.holomorphicMatrixEval_congr_on_neighborhood
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0059 :=
  @CrouzeixConjecture.holomorphicMatrixEval_congr_on_neighborhood
#check CrouzeixConjecture.holomorphicMatrixEval_mul
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0060 :=
  @CrouzeixConjecture.holomorphicMatrixEval_mul
#check CrouzeixConjecture.holomorphicMatrixEval_polynomial
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0061 :=
  @CrouzeixConjecture.holomorphicMatrixEval_polynomial
#check CrouzeixConjecture.inner_euclideanOperator_eq_star_dotProduct
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0062 :=
  @CrouzeixConjecture.inner_euclideanOperator_eq_star_dotProduct
#check CrouzeixConjecture.isCompact_numericalRange
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0063 :=
  @CrouzeixConjecture.isCompact_numericalRange
#check CrouzeixConjecture.isOpen_compl_rationalPoleSet
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0064 :=
  @CrouzeixConjecture.isOpen_compl_rationalPoleSet
#check CrouzeixConjecture.loristSchwenningerClosedOperatorNumericalRange_isTwoSpectralSet
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0065 :=
  @CrouzeixConjecture.loristSchwenningerClosedOperatorNumericalRange_isTwoSpectralSet
#check CrouzeixConjecture.loristSchwenningerFiniteMatrixMainTheorem
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0066 :=
  @CrouzeixConjecture.loristSchwenningerFiniteMatrixMainTheorem
#check CrouzeixConjecture.loristSchwenningerHilbertSpacePolynomialCrouzeix
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0067 :=
  @CrouzeixConjecture.loristSchwenningerHilbertSpacePolynomialCrouzeix
#check CrouzeixConjecture.loristSchwenningerMainTheorem
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0068 :=
  @CrouzeixConjecture.loristSchwenningerMainTheorem
#check CrouzeixConjecture.loristSchwenningerRationalSpectralSetCorollary
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0069 :=
  @CrouzeixConjecture.loristSchwenningerRationalSpectralSetCorollary
#check CrouzeixConjecture.matrixHerglotzKernel_isPositiveMatrixKernelOn
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0070 :=
  @CrouzeixConjecture.matrixHerglotzKernel_isPositiveMatrixKernelOn
#check CrouzeixConjecture.matrixPowerSeriesSum_analyticOnNhd_unitDisk
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0071 :=
  @CrouzeixConjecture.matrixPowerSeriesSum_analyticOnNhd_unitDisk
#check CrouzeixConjecture.matrixPowerSeries_apply
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0072 :=
  @CrouzeixConjecture.matrixPowerSeries_apply
#check CrouzeixConjecture.matrixPowerSeries_hasSum
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0073 :=
  @CrouzeixConjecture.matrixPowerSeries_hasSum
#check CrouzeixConjecture.matrixSpectrum_subset_numericalRange
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0074 :=
  @CrouzeixConjecture.matrixSpectrum_subset_numericalRange
#check CrouzeixConjecture.matrix_norm_eq_euclidean_operator_norm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0075 :=
  @CrouzeixConjecture.matrix_norm_eq_euclidean_operator_norm
#check CrouzeixConjecture.matrix_norm_le_two_of_four_sub_conjTranspose_mul_self_posSemidef
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0076 :=
  @CrouzeixConjecture.matrix_norm_le_two_of_four_sub_conjTranspose_mul_self_posSemidef
#check CrouzeixConjecture.maxFunctionModulusOnSet_mono
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0077 :=
  @CrouzeixConjecture.maxFunctionModulusOnSet_mono
#check CrouzeixConjecture.maxFunctionModulusOnSet_nonneg
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0078 :=
  @CrouzeixConjecture.maxFunctionModulusOnSet_nonneg
#check CrouzeixConjecture.norm_convexProjection_sub_le
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0079 :=
  @CrouzeixConjecture.norm_convexProjection_sub_le
#check CrouzeixConjecture.norm_function_le_maxFunctionModulusOnSet
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0080 :=
  @CrouzeixConjecture.norm_function_le_maxFunctionModulusOnSet
#check CrouzeixConjecture.norm_simpleSpectrumApproximation_sub_lt
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0081 :=
  @CrouzeixConjecture.norm_simpleSpectrumApproximation_sub_lt
#check CrouzeixConjecture.numericalRange_convex
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0082 :=
  @CrouzeixConjecture.numericalRange_convex
#check CrouzeixConjecture.numericalRange_eq_image_sphere
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0083 :=
  @CrouzeixConjecture.numericalRange_eq_image_sphere
#check CrouzeixConjecture.numericalRange_nonempty
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0084 :=
  @CrouzeixConjecture.numericalRange_nonempty
#check CrouzeixConjecture.numericalRange_perturbation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0085 :=
  @CrouzeixConjecture.numericalRange_perturbation
#check CrouzeixConjecture.one_le_matrixPowerSeries_radius
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0086 :=
  @CrouzeixConjecture.one_le_matrixPowerSeries_radius
#check CrouzeixConjecture.operatorNumericalRange_convex
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0087 :=
  @CrouzeixConjecture.operatorNumericalRange_convex
#check CrouzeixConjecture.parallelRadialParameterPoint_slice_hasDerivAt
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0088 :=
  @CrouzeixConjecture.parallelRadialParameterPoint_slice_hasDerivAt
#check CrouzeixConjecture.polynomialCrouzeixBound_of_holomorphicCrouzeixBound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0089 :=
  @CrouzeixConjecture.polynomialCrouzeixBound_of_holomorphicCrouzeixBound
#check CrouzeixConjecture.polynomialEval_diagonal
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0090 :=
  @CrouzeixConjecture.polynomialEval_diagonal
#check CrouzeixConjecture.posSemidef_congruence
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0091 :=
  @CrouzeixConjecture.posSemidef_congruence
#check CrouzeixConjecture.positiveRealCompletionStatement
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0092 :=
  @CrouzeixConjecture.positiveRealCompletionStatement
#check CrouzeixConjecture.radialTangent_eq_I_mul_normal_mul_norm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0093 :=
  @CrouzeixConjecture.radialTangent_eq_I_mul_normal_mul_norm
#check CrouzeixConjecture.rationalPoleSet_finite
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0094 :=
  @CrouzeixConjecture.rationalPoleSet_finite
#check CrouzeixConjecture.scalar_sub_matrix_isUnit_of_outwardBoundarySupport
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0095 :=
  @CrouzeixConjecture.scalar_sub_matrix_isUnit_of_outwardBoundarySupport
#check CrouzeixConjecture.simpleSpectrumApproximation_hasDistinctEigenvalues
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0096 :=
  @CrouzeixConjecture.simpleSpectrumApproximation_hasDistinctEigenvalues
#check CrouzeixConjecture.summable_gramianTerm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0097 :=
  @CrouzeixConjecture.summable_gramianTerm
#check CrouzeixConjecture.tendsto_maxFunctionModulusOnSet_of_outerApproximation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0098 :=
  @CrouzeixConjecture.tendsto_maxFunctionModulusOnSet_of_outerApproximation
#check CrouzeixConjecture.tendsto_parametricBoundaryIntegral_simpleSpectrumApproximation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0099 :=
  @CrouzeixConjecture.tendsto_parametricBoundaryIntegral_simpleSpectrumApproximation
#check CrouzeixConjecture.tendsto_simpleSpectrumApproximation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0100 :=
  @CrouzeixConjecture.tendsto_simpleSpectrumApproximation
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0101 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_01_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0102 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_02_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0103 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_03_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0104 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_04_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0105 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_05_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0106 :=
  @CrouzeixTextbook.Part01.Exercises.Chapter01.exercise_06_solution
#check CrouzeixTextbook.Part01.LinearTransformation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0107 :=
  @CrouzeixTextbook.Part01.LinearTransformation
#check CrouzeixTextbook.Part01.basis_coordinates_unique
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0108 :=
  @CrouzeixTextbook.Part01.basis_coordinates_unique
#check CrouzeixTextbook.Part01.change_basis_action
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0109 :=
  @CrouzeixTextbook.Part01.change_basis_action
#check CrouzeixTextbook.Part01.composition_range_le
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0110 :=
  @CrouzeixTextbook.Part01.composition_range_le
#check CrouzeixTextbook.Part01.coordinate_action_eq_mulVec
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0111 :=
  @CrouzeixTextbook.Part01.coordinate_action_eq_mulVec
#check CrouzeixTextbook.Part01.coordinate_change_conjugacy
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0112 :=
  @CrouzeixTextbook.Part01.coordinate_change_conjugacy
#check CrouzeixTextbook.Part01.determinant_diagonal
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0113 :=
  @CrouzeixTextbook.Part01.determinant_diagonal
#check CrouzeixTextbook.Part01.determinant_multiplicative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0114 :=
  @CrouzeixTextbook.Part01.determinant_multiplicative
#check CrouzeixTextbook.Part01.determinant_similarity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0115 :=
  @CrouzeixTextbook.Part01.determinant_similarity
#check CrouzeixTextbook.Part01.diagonalizable_polynomial_calculus
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0116 :=
  @CrouzeixTextbook.Part01.diagonalizable_polynomial_calculus
#check CrouzeixTextbook.Part01.diagonalization_eigenvalue_mem_spectrum
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0117 :=
  @CrouzeixTextbook.Part01.diagonalization_eigenvalue_mem_spectrum
#check CrouzeixTextbook.Part01.dimension_invariant_under_linear_equiv
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0118 :=
  @CrouzeixTextbook.Part01.dimension_invariant_under_linear_equiv
#check CrouzeixTextbook.Part01.direct_sum_coordinates_unique
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0119 :=
  @CrouzeixTextbook.Part01.direct_sum_coordinates_unique
#check CrouzeixTextbook.Part01.dual_map_apply
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0120 :=
  @CrouzeixTextbook.Part01.dual_map_apply
#check CrouzeixTextbook.Part01.dual_map_composition
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0121 :=
  @CrouzeixTextbook.Part01.dual_map_composition
#check CrouzeixTextbook.Part01.duality_similarity_preserves_charpoly
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0122 :=
  @CrouzeixTextbook.Part01.duality_similarity_preserves_charpoly
#check CrouzeixTextbook.Part01.generated_algebra_polynomial_representation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0123 :=
  @CrouzeixTextbook.Part01.generated_algebra_polynomial_representation
#check CrouzeixTextbook.Part01.injective_iff_kernel_bottom
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0124 :=
  @CrouzeixTextbook.Part01.injective_iff_kernel_bottom
#check CrouzeixTextbook.Part01.invariantRestriction
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0125 :=
  @CrouzeixTextbook.Part01.invariantRestriction
#check CrouzeixTextbook.Part01.matrix_column_is_basis_image
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0126 :=
  @CrouzeixTextbook.Part01.matrix_column_is_basis_image
#check CrouzeixTextbook.Part01.mem_kernel_iff
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0127 :=
  @CrouzeixTextbook.Part01.mem_kernel_iff
#check CrouzeixTextbook.Part01.mem_range_iff
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0128 :=
  @CrouzeixTextbook.Part01.mem_range_iff
#check CrouzeixTextbook.Part01.mem_subspace_intersection_iff
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0129 :=
  @CrouzeixTextbook.Part01.mem_subspace_intersection_iff
#check CrouzeixTextbook.Part01.nonunitary_similarity_changes_output_length_sq
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0130 :=
  @CrouzeixTextbook.Part01.nonunitary_similarity_changes_output_length_sq
#check CrouzeixTextbook.Part01.polynomial_action_diagonal
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0131 :=
  @CrouzeixTextbook.Part01.polynomial_action_diagonal
#check CrouzeixTextbook.Part01.polynomial_action_mem_generated_algebra
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0132 :=
  @CrouzeixTextbook.Part01.polynomial_action_mem_generated_algebra
#check CrouzeixTextbook.Part01.quotient_projection_surjective
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0133 :=
  @CrouzeixTextbook.Part01.quotient_projection_surjective
#check CrouzeixTextbook.Part01.rank_nullity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0134 :=
  @CrouzeixTextbook.Part01.rank_nullity
#check CrouzeixTextbook.Part01.similarity_preserves_charpoly
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0135 :=
  @CrouzeixTextbook.Part01.similarity_preserves_charpoly
#check CrouzeixTextbook.Part01.similarity_preserves_determinant
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0136 :=
  @CrouzeixTextbook.Part01.similarity_preserves_determinant
#check CrouzeixTextbook.Part01.similarity_preserves_trace
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0137 :=
  @CrouzeixTextbook.Part01.similarity_preserves_trace
#check CrouzeixTextbook.Part01.simple_spectrum_dense
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0138 :=
  @CrouzeixTextbook.Part01.simple_spectrum_dense
#check CrouzeixTextbook.Part01.span_minimality
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0139 :=
  @CrouzeixTextbook.Part01.span_minimality
#check CrouzeixTextbook.Part01.trace_cyclic
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0140 :=
  @CrouzeixTextbook.Part01.trace_cyclic
#check CrouzeixTextbook.Part01.trace_diagonal
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0141 :=
  @CrouzeixTextbook.Part01.trace_diagonal
#check CrouzeixTextbook.Part01.trace_similarity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0142 :=
  @CrouzeixTextbook.Part01.trace_similarity
#check CrouzeixTextbook.Part02.adjoint_coordinate_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0143 :=
  @CrouzeixTextbook.Part02.adjoint_coordinate_identity
#check CrouzeixTextbook.Part02.adjoint_matrix_is_conjugate_transpose
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0144 :=
  @CrouzeixTextbook.Part02.adjoint_matrix_is_conjugate_transpose
#check CrouzeixTextbook.Part02.alternating_diagonal_volume
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0145 :=
  @CrouzeixTextbook.Part02.alternating_diagonal_volume
#check CrouzeixTextbook.Part02.area_form_quarter_turn
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0146 :=
  @CrouzeixTextbook.Part02.area_form_quarter_turn
#check CrouzeixTextbook.Part02.bilinear_pairing_duality
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0147 :=
  @CrouzeixTextbook.Part02.bilinear_pairing_duality
#check CrouzeixTextbook.Part02.boundary_parameter_is_smooth
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0148 :=
  @CrouzeixTextbook.Part02.boundary_parameter_is_smooth
#check CrouzeixTextbook.Part02.boundary_slice_derivative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0149 :=
  @CrouzeixTextbook.Part02.boundary_slice_derivative
#check CrouzeixTextbook.Part02.contraction_trace_cyclic
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0150 :=
  @CrouzeixTextbook.Part02.contraction_trace_cyclic
#check CrouzeixTextbook.Part02.derivative_action_is_jvp
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0151 :=
  @CrouzeixTextbook.Part02.derivative_action_is_jvp
#check CrouzeixTextbook.Part02.derivative_pullback_is_vjp
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0152 :=
  @CrouzeixTextbook.Part02.derivative_pullback_is_vjp
#check CrouzeixTextbook.Part02.determinant_top_degree_multiplicative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0153 :=
  @CrouzeixTextbook.Part02.determinant_top_degree_multiplicative
#check CrouzeixTextbook.Part02.gradient_component_contract
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0154 :=
  @CrouzeixTextbook.Part02.gradient_component_contract
#check CrouzeixTextbook.Part02.gram_matrix_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0155 :=
  @CrouzeixTextbook.Part02.gram_matrix_positive
#check CrouzeixTextbook.Part02.hessian_vector_action
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0156 :=
  @CrouzeixTextbook.Part02.hessian_vector_action
#check CrouzeixTextbook.Part02.induced_matrix_norm_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0157 :=
  @CrouzeixTextbook.Part02.induced_matrix_norm_identity
#check CrouzeixTextbook.Part02.invertible_gram_matrix_invertible
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0158 :=
  @CrouzeixTextbook.Part02.invertible_gram_matrix_invertible
#check CrouzeixTextbook.Part02.invertible_gram_matrix_positive_definite
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0159 :=
  @CrouzeixTextbook.Part02.invertible_gram_matrix_positive_definite
#check CrouzeixTextbook.Part02.jvp_vjp_duality
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0160 :=
  @CrouzeixTextbook.Part02.jvp_vjp_duality
#check CrouzeixTextbook.Part02.linear_approximation_chain_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0161 :=
  @CrouzeixTextbook.Part02.linear_approximation_chain_kernel
#check CrouzeixTextbook.Part02.matrix_norm_is_operator_norm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0162 :=
  @CrouzeixTextbook.Part02.matrix_norm_is_operator_norm
#check CrouzeixTextbook.Part02.norm_is_nonnegative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0163 :=
  @CrouzeixTextbook.Part02.norm_is_nonnegative
#check CrouzeixTextbook.Part02.norm_triangle_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0164 :=
  @CrouzeixTextbook.Part02.norm_triangle_kernel
#check CrouzeixTextbook.Part02.oriented_radial_tangent_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0165 :=
  @CrouzeixTextbook.Part02.oriented_radial_tangent_positive
#check CrouzeixTextbook.Part02.oriented_tangent_formula
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0166 :=
  @CrouzeixTextbook.Part02.oriented_tangent_formula
#check CrouzeixTextbook.Part02.polar_factor_is_unitary
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0167 :=
  @CrouzeixTextbook.Part02.polar_factor_is_unitary
#check CrouzeixTextbook.Part02.polar_operator_norm_transfer
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0168 :=
  @CrouzeixTextbook.Part02.polar_operator_norm_transfer
#check CrouzeixTextbook.Part02.polar_similarity_norm_transfer
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0169 :=
  @CrouzeixTextbook.Part02.polar_similarity_norm_transfer
#check CrouzeixTextbook.Part02.positive_definite_quadratic_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0170 :=
  @CrouzeixTextbook.Part02.positive_definite_quadratic_positive
#check CrouzeixTextbook.Part02.positive_square_root_data
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0171 :=
  @CrouzeixTextbook.Part02.positive_square_root_data
#check CrouzeixTextbook.Part02.positivity_preserved_by_congruence
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0172 :=
  @CrouzeixTextbook.Part02.positivity_preserved_by_congruence
#check CrouzeixTextbook.Part02.projection_residual_decomposition
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0173 :=
  @CrouzeixTextbook.Part02.projection_residual_decomposition
#check CrouzeixTextbook.Part02.projection_residual_orthogonal
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0174 :=
  @CrouzeixTextbook.Part02.projection_residual_orthogonal
#check CrouzeixTextbook.Part02.quadratic_bound_implies_norm_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0175 :=
  @CrouzeixTextbook.Part02.quadratic_bound_implies_norm_two
#check CrouzeixTextbook.Part02.real_inner_complex_coordinates
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0176 :=
  @CrouzeixTextbook.Part02.real_inner_complex_coordinates
#check CrouzeixTextbook.Part02.transpose_coordinate_action
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0177 :=
  @CrouzeixTextbook.Part02.transpose_coordinate_action
#check CrouzeixTextbook.Part02.wedge_sign_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0178 :=
  @CrouzeixTextbook.Part02.wedge_sign_kernel
#check CrouzeixTextbook.Part03.boundary_integral_continuous
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0179 :=
  @CrouzeixTextbook.Part03.boundary_integral_continuous
#check CrouzeixTextbook.Part03.boundary_integral_is_function_eval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0180 :=
  @CrouzeixTextbook.Part03.boundary_integral_is_function_eval
#check CrouzeixTextbook.Part03.compact_maximum_exists
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0181 :=
  @CrouzeixTextbook.Part03.compact_maximum_exists
#check CrouzeixTextbook.Part03.compact_maximum_monotone
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0182 :=
  @CrouzeixTextbook.Part03.compact_maximum_monotone
#check CrouzeixTextbook.Part03.compact_maximum_nonnegative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0183 :=
  @CrouzeixTextbook.Part03.compact_maximum_nonnegative
#check CrouzeixTextbook.Part03.contour_eval_agrees
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0184 :=
  @CrouzeixTextbook.Part03.contour_eval_agrees
#check CrouzeixTextbook.Part03.functional_calculus_additive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0185 :=
  @CrouzeixTextbook.Part03.functional_calculus_additive
#check CrouzeixTextbook.Part03.functional_calculus_multiplicative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0186 :=
  @CrouzeixTextbook.Part03.functional_calculus_multiplicative
#check CrouzeixTextbook.Part03.holomorphic_matrix_eval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0187 :=
  @CrouzeixTextbook.Part03.holomorphic_matrix_eval
#check CrouzeixTextbook.Part03.locality_on_neighborhood
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0188 :=
  @CrouzeixTextbook.Part03.locality_on_neighborhood
#check CrouzeixTextbook.Part03.matrix_herglotz_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0189 :=
  @CrouzeixTextbook.Part03.matrix_herglotz_kernel
#check CrouzeixTextbook.Part03.matrix_herglotz_kernel_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0190 :=
  @CrouzeixTextbook.Part03.matrix_herglotz_kernel_positive
#check CrouzeixTextbook.Part03.matrix_power_series
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0191 :=
  @CrouzeixTextbook.Part03.matrix_power_series
#check CrouzeixTextbook.Part03.matrix_power_series_analytic
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0192 :=
  @CrouzeixTextbook.Part03.matrix_power_series_analytic
#check CrouzeixTextbook.Part03.matrix_power_series_coefficient
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0193 :=
  @CrouzeixTextbook.Part03.matrix_power_series_coefficient
#check CrouzeixTextbook.Part03.matrix_power_series_converges
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0194 :=
  @CrouzeixTextbook.Part03.matrix_power_series_converges
#check CrouzeixTextbook.Part03.matrix_power_series_radius
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0195 :=
  @CrouzeixTextbook.Part03.matrix_power_series_radius
#check CrouzeixTextbook.Part03.matrix_power_series_sum
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0196 :=
  @CrouzeixTextbook.Part03.matrix_power_series_sum
#check CrouzeixTextbook.Part03.max_modulus_on_compact_set
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0197 :=
  @CrouzeixTextbook.Part03.max_modulus_on_compact_set
#check CrouzeixTextbook.Part03.open_unit_disk
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0198 :=
  @CrouzeixTextbook.Part03.open_unit_disk
#check CrouzeixTextbook.Part03.outer_maxima_converge
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0199 :=
  @CrouzeixTextbook.Part03.outer_maxima_converge
#check CrouzeixTextbook.Part03.parametric_boundary_integral
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0200 :=
  @CrouzeixTextbook.Part03.parametric_boundary_integral
#check CrouzeixTextbook.Part03.pointwise_norm_le_maximum
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0201 :=
  @CrouzeixTextbook.Part03.pointwise_norm_le_maximum
#check CrouzeixTextbook.Part03.pole_complement_open
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0202 :=
  @CrouzeixTextbook.Part03.pole_complement_open
#check CrouzeixTextbook.Part03.polynomial_compatibility
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0203 :=
  @CrouzeixTextbook.Part03.polynomial_compatibility
#check CrouzeixTextbook.Part03.positive_matrix_kernel_on
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0204 :=
  @CrouzeixTextbook.Part03.positive_matrix_kernel_on
#check CrouzeixTextbook.Part03.rational_matrix_eval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0205 :=
  @CrouzeixTextbook.Part03.rational_matrix_eval
#check CrouzeixTextbook.Part03.rational_pole_free_on
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0206 :=
  @CrouzeixTextbook.Part03.rational_pole_free_on
#check CrouzeixTextbook.Part03.rational_pole_set
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0207 :=
  @CrouzeixTextbook.Part03.rational_pole_set
#check CrouzeixTextbook.Part03.rational_poles_finite
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0208 :=
  @CrouzeixTextbook.Part03.rational_poles_finite
#check CrouzeixTextbook.Part03.rational_scalar_eval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0209 :=
  @CrouzeixTextbook.Part03.rational_scalar_eval
#check CrouzeixTextbook.Part03.sampled_kernel_matrix
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0210 :=
  @CrouzeixTextbook.Part03.sampled_kernel_matrix
#check CrouzeixTextbook.Part03.simple_spectrum_boundary_limit
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0211 :=
  @CrouzeixTextbook.Part03.simple_spectrum_boundary_limit
#check CrouzeixTextbook.Part03.simple_spectrum_eval_limit
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0212 :=
  @CrouzeixTextbook.Part03.simple_spectrum_eval_limit
#check CrouzeixTextbook.Part03.simple_spectrum_holomorphic_eval
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0213 :=
  @CrouzeixTextbook.Part03.simple_spectrum_holomorphic_eval
#check CrouzeixTextbook.Part03.unit_circle
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0214 :=
  @CrouzeixTextbook.Part03.unit_circle
#check CrouzeixTextbook.Part04.adjacent_power_defect_factorization
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0215 :=
  @CrouzeixTextbook.Part04.adjacent_power_defect_factorization
#check CrouzeixTextbook.Part04.boundary_positive_linear_map
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0216 :=
  @CrouzeixTextbook.Part04.boundary_positive_linear_map
#check CrouzeixTextbook.Part04.boundary_positive_map
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0217 :=
  @CrouzeixTextbook.Part04.boundary_positive_map
#check CrouzeixTextbook.Part04.boundary_positive_map_norm
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0218 :=
  @CrouzeixTextbook.Part04.boundary_positive_map_norm
#check CrouzeixTextbook.Part04.boundary_positive_map_preserves_psd
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0219 :=
  @CrouzeixTextbook.Part04.boundary_positive_map_preserves_psd
#check CrouzeixTextbook.Part04.boundary_positive_map_star
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0220 :=
  @CrouzeixTextbook.Part04.boundary_positive_map_star
#check CrouzeixTextbook.Part04.boundary_positive_map_unital
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0221 :=
  @CrouzeixTextbook.Part04.boundary_positive_map_unital
#check CrouzeixTextbook.Part04.closed_numerical_range_two_spectral_set
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0222 :=
  @CrouzeixTextbook.Part04.closed_numerical_range_two_spectral_set
#check CrouzeixTextbook.Part04.closed_operator_numerical_range
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0223 :=
  @CrouzeixTextbook.Part04.closed_operator_numerical_range
#check CrouzeixTextbook.Part04.closed_operator_numerical_range_compact
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0224 :=
  @CrouzeixTextbook.Part04.closed_operator_numerical_range_compact
#check CrouzeixTextbook.Part04.closed_operator_numerical_range_nonempty
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0225 :=
  @CrouzeixTextbook.Part04.closed_operator_numerical_range_nonempty
#check CrouzeixTextbook.Part04.compressed_adjoint_power
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0226 :=
  @CrouzeixTextbook.Part04.compressed_adjoint_power
#check CrouzeixTextbook.Part04.compressed_adjoint_power_contractive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0227 :=
  @CrouzeixTextbook.Part04.compressed_adjoint_power_contractive
#check CrouzeixTextbook.Part04.diagonal_polynomial_action
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0228 :=
  @CrouzeixTextbook.Part04.diagonal_polynomial_action
#check CrouzeixTextbook.Part04.distinct_spectrum_dense
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0229 :=
  @CrouzeixTextbook.Part04.distinct_spectrum_dense
#check CrouzeixTextbook.Part04.doubled_compression_norm_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0230 :=
  @CrouzeixTextbook.Part04.doubled_compression_norm_two
#check CrouzeixTextbook.Part04.gramian_difference_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0231 :=
  @CrouzeixTextbook.Part04.gramian_difference_positive
#check CrouzeixTextbook.Part04.gramian_term
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0232 :=
  @CrouzeixTextbook.Part04.gramian_term
#check CrouzeixTextbook.Part04.gramian_term_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0233 :=
  @CrouzeixTextbook.Part04.gramian_term_positive
#check CrouzeixTextbook.Part04.gramian_terms_summable
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0234 :=
  @CrouzeixTextbook.Part04.gramian_terms_summable
#check CrouzeixTextbook.Part04.hilbert_rational_spectral_set_statement
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0235 :=
  @CrouzeixTextbook.Part04.hilbert_rational_spectral_set_statement
#check CrouzeixTextbook.Part04.numerical_range_as_sphere_image
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0236 :=
  @CrouzeixTextbook.Part04.numerical_range_as_sphere_image
#check CrouzeixTextbook.Part04.numerical_range_compact
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0237 :=
  @CrouzeixTextbook.Part04.numerical_range_compact
#check CrouzeixTextbook.Part04.numerical_range_convex
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0238 :=
  @CrouzeixTextbook.Part04.numerical_range_convex
#check CrouzeixTextbook.Part04.numerical_range_nonempty
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0239 :=
  @CrouzeixTextbook.Part04.numerical_range_nonempty
#check CrouzeixTextbook.Part04.numerical_range_perturbation_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0240 :=
  @CrouzeixTextbook.Part04.numerical_range_perturbation_bound
#check CrouzeixTextbook.Part04.operator_numerical_range_convex
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0241 :=
  @CrouzeixTextbook.Part04.operator_numerical_range_convex
#check CrouzeixTextbook.Part04.perturbation_commutes
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0242 :=
  @CrouzeixTextbook.Part04.perturbation_commutes
#check CrouzeixTextbook.Part04.simple_spectrum_approximation
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0243 :=
  @CrouzeixTextbook.Part04.simple_spectrum_approximation
#check CrouzeixTextbook.Part04.simple_spectrum_approximation_close
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0244 :=
  @CrouzeixTextbook.Part04.simple_spectrum_approximation_close
#check CrouzeixTextbook.Part04.simple_spectrum_approximation_converges
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0245 :=
  @CrouzeixTextbook.Part04.simple_spectrum_approximation_converges
#check CrouzeixTextbook.Part04.simple_spectrum_approximation_distinct
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0246 :=
  @CrouzeixTextbook.Part04.simple_spectrum_approximation_distinct
#check CrouzeixTextbook.Part04.spectrum_lies_in_numerical_range
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0247 :=
  @CrouzeixTextbook.Part04.spectrum_lies_in_numerical_range
#check CrouzeixTextbook.Part04.target_power_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0248 :=
  @CrouzeixTextbook.Part04.target_power_bound
#check CrouzeixTextbook.Part04.weighted_gramian
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0249 :=
  @CrouzeixTextbook.Part04.weighted_gramian
#check CrouzeixTextbook.Part04.weighted_gramian_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0250 :=
  @CrouzeixTextbook.Part04.weighted_gramian_positive
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0251 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_01_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0252 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_02_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0253 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_03_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0254 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_04_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0255 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_05_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0256 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter25.exercise_06_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0257 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_01_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0258 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_02_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0259 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_03_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0260 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_04_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0261 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_05_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0262 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter26.exercise_06_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0263 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_01_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0264 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_02_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0265 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_03_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0266 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_04_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0267 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_05_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0268 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter27.exercise_06_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0269 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_01_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0270 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_02_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0271 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_03_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0272 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_04_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0273 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_05_solution
#check CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0274 :=
  @CrouzeixTextbook.Part05.Exercises.Chapter28.exercise_06_solution
#check CrouzeixTextbook.Part05.contractive_boundary_function
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0275 :=
  @CrouzeixTextbook.Part05.contractive_boundary_function
#check CrouzeixTextbook.Part05.convex_projection
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0276 :=
  @CrouzeixTextbook.Part05.convex_projection
#check CrouzeixTextbook.Part05.convex_projection_nonexpansive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0277 :=
  @CrouzeixTextbook.Part05.convex_projection_nonexpansive
#check CrouzeixTextbook.Part05.convex_projection_variational
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0278 :=
  @CrouzeixTextbook.Part05.convex_projection_variational
#check CrouzeixTextbook.Part05.double_layer_congruence
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0279 :=
  @CrouzeixTextbook.Part05.double_layer_congruence
#check CrouzeixTextbook.Part05.double_layer_density_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0280 :=
  @CrouzeixTextbook.Part05.double_layer_density_positive
#check CrouzeixTextbook.Part05.double_layer_resolvent
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0281 :=
  @CrouzeixTextbook.Part05.double_layer_resolvent
#check CrouzeixTextbook.Part05.double_layer_support_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0282 :=
  @CrouzeixTextbook.Part05.double_layer_support_positive
#check CrouzeixTextbook.Part05.one_plus_sqrt_two_barrier
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0283 :=
  @CrouzeixTextbook.Part05.one_plus_sqrt_two_barrier
#check CrouzeixTextbook.Part05.one_plus_sqrt_two_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0284 :=
  @CrouzeixTextbook.Part05.one_plus_sqrt_two_positive
#check CrouzeixTextbook.Part05.outer_approximation_radius
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0285 :=
  @CrouzeixTextbook.Part05.outer_approximation_radius
#check CrouzeixTextbook.Part05.outer_radius_tends_to_zero
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0286 :=
  @CrouzeixTextbook.Part05.outer_radius_tends_to_zero
#check CrouzeixTextbook.Part05.parallel_outer_domain_data
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0287 :=
  @CrouzeixTextbook.Part05.parallel_outer_domain_data
#check CrouzeixTextbook.Part05.positive_completion_from_power_family
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0288 :=
  @CrouzeixTextbook.Part05.positive_completion_from_power_family
#check CrouzeixTextbook.Part05.positive_map_norm_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0289 :=
  @CrouzeixTextbook.Part05.positive_map_norm_kernel
#check CrouzeixTextbook.Part05.power_cauchy_formula
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0290 :=
  @CrouzeixTextbook.Part05.power_cauchy_formula
#check CrouzeixTextbook.Part05.power_cauchy_mass_one
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0291 :=
  @CrouzeixTextbook.Part05.power_cauchy_mass_one
#check CrouzeixTextbook.Part05.power_cayley_companion
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0292 :=
  @CrouzeixTextbook.Part05.power_cayley_companion
#check CrouzeixTextbook.Part05.power_family_norm_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0293 :=
  @CrouzeixTextbook.Part05.power_family_norm_two
#check CrouzeixTextbook.Part05.sqrt_two_nonnegative
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0294 :=
  @CrouzeixTextbook.Part05.sqrt_two_nonnegative
#check CrouzeixTextbook.Part05.sqrt_two_squared
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0295 :=
  @CrouzeixTextbook.Part05.sqrt_two_squared
#check CrouzeixTextbook.Part05.support_point_outside_numerical_range
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0296 :=
  @CrouzeixTextbook.Part05.support_point_outside_numerical_range
#check CrouzeixTextbook.Part05.support_resolvent_invertible
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0297 :=
  @CrouzeixTextbook.Part05.support_resolvent_invertible
#check CrouzeixTextbook.Part05.triangle_barrier_kernel
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0298 :=
  @CrouzeixTextbook.Part05.triangle_barrier_kernel
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0299 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0300 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0301 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0302 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0303 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0304 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter29.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0305 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0306 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0307 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0308 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0309 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0310 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter30.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0311 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0312 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0313 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0314 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0315 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0316 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter31.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0317 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0318 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0319 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0320 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0321 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0322 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter32.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0323 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0324 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0325 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0326 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0327 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0328 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter33.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0329 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0330 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0331 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0332 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0333 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0334 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter34.exercise_06_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_01_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0335 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_01_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_02_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0336 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_02_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_03_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0337 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_03_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_04_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0338 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_04_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_05_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0339 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_05_solution
#check CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_06_solution
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0340 :=
  @CrouzeixTextbook.Part06.Exercises.Chapter35.exercise_06_solution
#check CrouzeixTextbook.Part06.boundary_compression_first_moment
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0341 :=
  @CrouzeixTextbook.Part06.boundary_compression_first_moment
#check CrouzeixTextbook.Part06.boundary_compression_power_moments
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0342 :=
  @CrouzeixTextbook.Part06.boundary_compression_power_moments
#check CrouzeixTextbook.Part06.boundary_dilation_data
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0343 :=
  @CrouzeixTextbook.Part06.boundary_dilation_data
#check CrouzeixTextbook.Part06.boundary_multiplier_contractive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0344 :=
  @CrouzeixTextbook.Part06.boundary_multiplier_contractive
#check CrouzeixTextbook.Part06.boundary_multiplier_powers
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0345 :=
  @CrouzeixTextbook.Part06.boundary_multiplier_powers
#check CrouzeixTextbook.Part06.completion_gramian_difference
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0346 :=
  @CrouzeixTextbook.Part06.completion_gramian_difference
#check CrouzeixTextbook.Part06.completion_gramian_four
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0347 :=
  @CrouzeixTextbook.Part06.completion_gramian_four
#check CrouzeixTextbook.Part06.completion_gramian_source_positive
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0348 :=
  @CrouzeixTextbook.Part06.completion_gramian_source_positive
#check CrouzeixTextbook.Part06.completion_gramian_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0349 :=
  @CrouzeixTextbook.Part06.completion_gramian_two
#check CrouzeixTextbook.Part06.completion_implies_norm_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0350 :=
  @CrouzeixTextbook.Part06.completion_implies_norm_two
#check CrouzeixTextbook.Part06.completion_kernel_model
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0351 :=
  @CrouzeixTextbook.Part06.completion_kernel_model
#check CrouzeixTextbook.Part06.completion_kernel_normalization_forces_correction_zero
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0352 :=
  @CrouzeixTextbook.Part06.completion_kernel_normalization_forces_correction_zero
#check CrouzeixTextbook.Part06.constant_two_is_least
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0353 :=
  @CrouzeixTextbook.Part06.constant_two_is_least
#check CrouzeixTextbook.Part06.correction_sampling_cancels
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0354 :=
  @CrouzeixTextbook.Part06.correction_sampling_cancels
#check CrouzeixTextbook.Part06.correction_sampling_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0355 :=
  @CrouzeixTextbook.Part06.correction_sampling_identity
#check CrouzeixTextbook.Part06.equation_three_lower_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0356 :=
  @CrouzeixTextbook.Part06.equation_three_lower_bound
#check CrouzeixTextbook.Part06.holomorphic_constant_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0357 :=
  @CrouzeixTextbook.Part06.holomorphic_constant_two
#check CrouzeixTextbook.Part06.jin_polynomial_constant_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0358 :=
  @CrouzeixTextbook.Part06.jin_polynomial_constant_two
#check CrouzeixTextbook.Part06.jin_rational_constant_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0359 :=
  @CrouzeixTextbook.Part06.jin_rational_constant_two
#check CrouzeixTextbook.Part06.jin_rational_spectral_set
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0360 :=
  @CrouzeixTextbook.Part06.jin_rational_spectral_set
#check CrouzeixTextbook.Part06.jin_rational_spectral_set_provider
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0361 :=
  @CrouzeixTextbook.Part06.jin_rational_spectral_set_provider
#check CrouzeixTextbook.Part06.jordan_two_attains_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0362 :=
  @CrouzeixTextbook.Part06.jordan_two_attains_two
#check CrouzeixTextbook.Part06.jordan_two_maximum
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0363 :=
  @CrouzeixTextbook.Part06.jordan_two_maximum
#check CrouzeixTextbook.Part06.kernel_positivity_implies_X
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0364 :=
  @CrouzeixTextbook.Part06.kernel_positivity_implies_X
#check CrouzeixTextbook.Part06.lorist_schwenninger_finite_matrix
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0365 :=
  @CrouzeixTextbook.Part06.lorist_schwenninger_finite_matrix
#check CrouzeixTextbook.Part06.lorist_schwenninger_hilbert
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0366 :=
  @CrouzeixTextbook.Part06.lorist_schwenninger_hilbert
#check CrouzeixTextbook.Part06.lorist_schwenninger_main
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0367 :=
  @CrouzeixTextbook.Part06.lorist_schwenninger_main
#check CrouzeixTextbook.Part06.lorist_schwenninger_rational
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0368 :=
  @CrouzeixTextbook.Part06.lorist_schwenninger_rational
#check CrouzeixTextbook.Part06.lorist_schwenninger_two_spectral_set
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0369 :=
  @CrouzeixTextbook.Part06.lorist_schwenninger_two_spectral_set
#check CrouzeixTextbook.Part06.main_theorem_statement
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0370 :=
  @CrouzeixTextbook.Part06.main_theorem_statement
#check CrouzeixTextbook.Part06.max_polynomial_modulus
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0371 :=
  @CrouzeixTextbook.Part06.max_polynomial_modulus
#check CrouzeixTextbook.Part06.perturbation_lemma
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0372 :=
  @CrouzeixTextbook.Part06.perturbation_lemma
#check CrouzeixTextbook.Part06.polynomial_crouzeix_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0373 :=
  @CrouzeixTextbook.Part06.polynomial_crouzeix_bound
#check CrouzeixTextbook.Part06.polynomial_from_holomorphic
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0374 :=
  @CrouzeixTextbook.Part06.polynomial_from_holomorphic
#check CrouzeixTextbook.Part06.positive_real_completion
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0375 :=
  @CrouzeixTextbook.Part06.positive_real_completion
#check CrouzeixTextbook.Part06.positive_real_completion_statement
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0376 :=
  @CrouzeixTextbook.Part06.positive_real_completion_statement
#check CrouzeixTextbook.Part06.realization_norm_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0377 :=
  @CrouzeixTextbook.Part06.realization_norm_two
#check CrouzeixTextbook.Part06.recurrence_difference_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0378 :=
  @CrouzeixTextbook.Part06.recurrence_difference_identity
#check CrouzeixTextbook.Part06.recurrence_difference_lower_bound
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0379 :=
  @CrouzeixTextbook.Part06.recurrence_difference_lower_bound
#check CrouzeixTextbook.Part06.sample_origin_quadratic_identity
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0380 :=
  @CrouzeixTextbook.Part06.sample_origin_quadratic_identity
#check CrouzeixTextbook.Part06.scalar_combined_inequality
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0381 :=
  @CrouzeixTextbook.Part06.scalar_combined_inequality
#check CrouzeixTextbook.Part06.scalar_endpoint_two
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0382 :=
  @CrouzeixTextbook.Part06.scalar_endpoint_two
#check CrouzeixTextbook.Part06.three_route_terminal_bundle
noncomputable def CrouzeixTextbook.ReceiptMarker.declaration0383 :=
  @CrouzeixTextbook.Part06.three_route_terminal_bundle
