import CrouzeixConjecture.GeneratedAlgebra
import CrouzeixConjecture.SimpleSpectrumBridge
import CrouzeixConjecture.SimpleSpectrumDensity
import CrouzeixConjecture.Spectrum
import CrouzeixTextbook.Part01.Chapter05
import Mathlib.LinearAlgebra.Lagrange
import Mathlib.LinearAlgebra.Matrix.Charpoly.Eigs
import Mathlib.LinearAlgebra.Matrix.Charpoly.Minpoly

namespace CrouzeixTextbook.Part01

open CrouzeixConjecture
open scoped Matrix
open scoped Matrix.Norms.L2Operator

set_option linter.defProp false

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- CFT-06-001: polynomial action on a diagonal matrix is entrywise evaluation. -/
def polynomial_action_diagonal := @polynomialEval_diagonal

/-- CFT-06-002: polynomial action preserves an explicitly supplied eigenbasis. -/
def diagonalizable_polynomial_calculus := @SimpleDiagonalization.polynomialEval_eq_innerConjugation_diagonal

/-- CFT-06-003: every supplied eigenvalue belongs to the spectrum. -/
def diagonalization_eigenvalue_mem_spectrum := @SimpleDiagonalization.eigenvalue_mem_matrixSpectrum

/-- CFT-06-004: every polynomial action lies in the algebra generated by the matrix. -/
def polynomial_action_mem_generated_algebra := @polynomialEval_mem_generatedAlgebra

/-- CFT-06-005: the singly generated algebra consists exactly of polynomial actions. -/
def generated_algebra_polynomial_representation := @generatedAlgebra_mem_iff_exists_polynomial

/-- CFT-06-006: simple-spectrum matrices are dense in finite complex matrix space. -/
def simple_spectrum_dense := @exists_hasDistinctEigenvalues_norm_sub_lt

section SpectralSupport

variable {K m : Type*} [Field K] [Fintype m] [DecidableEq m]

/-- Spectrum test: the scalars in the spectrum are exactly the characteristic roots. -/
theorem spectrum_iff_charpoly_root (A : Matrix m m K) (r : K) :
    r ∈ spectrum K A ↔ A.charpoly.IsRoot r :=
  Matrix.mem_spectrum_iff_isRoot_charpoly

/-- Cayley--Hamilton: every matrix annihilates its own characteristic polynomial. -/
theorem charpoly_annihilates (A : Matrix m m K) :
    Polynomial.aeval A A.charpoly = 0 :=
  Matrix.aeval_self_charpoly A

/-- The minimal polynomial divides the characteristic polynomial. -/
theorem minimal_polynomial_dvd_charpoly (A : Matrix m m K) :
    minpoly K A ∣ A.charpoly :=
  Matrix.minpoly_dvd_charpoly A

/-- Division reduces every polynomial action below the characteristic degree. -/
theorem polynomial_action_reduces (A : Matrix m m K) (p : Polynomial K) :
    Polynomial.aeval A p = Polynomial.aeval A (p %ₘ A.charpoly) :=
  Matrix.aeval_eq_aeval_mod_charpoly A p

/-- The algebra generated by a single matrix is commutative. -/
theorem polynomial_actions_commute (A : Matrix m m K) (p q : Polynomial K) :
    Polynomial.aeval A p * Polynomial.aeval A q =
      Polynomial.aeval A q * Polynomial.aeval A p := by
  rw [← map_mul, ← map_mul, mul_comm p q]

/-- Powers act on an eigenvector by the corresponding powers of its eigenvalue. -/
theorem pow_mulVec_eigenvector {A : Matrix m m K} {v : m → K} {c : K}
    (h : A *ᵥ v = c • v) (k : ℕ) : (A ^ k) *ᵥ v = c ^ k • v := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [pow_succ, ← Matrix.mulVec_mulVec, h, Matrix.mulVec_smul, ih, smul_smul, pow_succ,
        mul_comm]

/-- Every polynomial action fixes an eigenvector and scales it by the evaluated polynomial. -/
theorem aeval_mulVec_eigenvector {A : Matrix m m K} {v : m → K} {c : K}
    (h : A *ᵥ v = c • v) (p : Polynomial K) :
    (Polynomial.aeval A p) *ᵥ v = (p.eval c) • v := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq =>
      rw [map_add, Polynomial.eval_add, Matrix.add_mulVec, hp, hq, add_smul]
  | monomial k a =>
      rw [Polynomial.aeval_monomial, Polynomial.eval_monomial, ← Algebra.smul_def,
        Matrix.smul_mulVec, pow_mulVec_eigenvector h k, smul_smul]

/-- A one-sided matrix inverse is automatically two-sided. -/
theorem left_inverse_is_two_sided {S R : Matrix m m K} (h : R * S = 1) : S * R = 1 :=
  mul_eq_one_comm.mpr h

/-- Conjugation transports powers, which is the engine of the diagonalizable calculus. -/
theorem conjugate_pow {S R A : Matrix m m K} (h : R * S = 1) (k : ℕ) :
    (S * A * R) ^ k = S * A ^ k * R := by
  induction k with
  | zero => simpa using (left_inverse_is_two_sided h).symm
  | succ k ih =>
      rw [pow_succ, ih, pow_succ]
      calc S * A ^ k * R * (S * A * R)
          = S * A ^ k * (R * S) * A * R := by
            simp only [Matrix.mul_assoc]
        _ = S * A ^ k * A * R := by rw [h, Matrix.mul_one]
        _ = S * (A ^ k * A) * R := by simp only [Matrix.mul_assoc]

/-- Conjugation transports every polynomial action, not only the powers. -/
theorem conjugate_aeval {S R A : Matrix m m K} (h : R * S = 1) (p : Polynomial K) :
    Polynomial.aeval (S * A * R) p = S * Polynomial.aeval A p * R := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq =>
      rw [map_add, hp, hq, map_add, Matrix.mul_add, Matrix.add_mul]
  | monomial k a =>
      rw [Polynomial.aeval_monomial, Polynomial.aeval_monomial, conjugate_pow h k]
      simp only [Matrix.mul_assoc]
      rw [← Matrix.mul_assoc, Algebra.commutes, Matrix.mul_assoc]

/-- Polynomial action on a diagonal matrix is entrywise scalar evaluation, over any field. -/
theorem aeval_diagonal (d : m → K) (p : Polynomial K) :
    Polynomial.aeval (Matrix.diagonal d) p =
      Matrix.diagonal (fun i => p.eval (d i)) := by
  calc Polynomial.aeval (Matrix.diagonal d) p
      = Matrix.diagonal (Polynomial.aeval d p) :=
        Polynomial.aeval_algHom_apply (Matrix.diagonalAlgHom K) d p
    _ = Matrix.diagonal (fun i => p.eval (d i)) := by
        congr 1
        funext i
        rw [Polynomial.aeval_pi_apply₂]
        exact Polynomial.coe_aeval_eq_eval (d i) ▸ rfl

/-- Lagrange interpolation supplies a polynomial with prescribed values at distinct nodes. -/
theorem exists_polynomial_with_prescribed_values {ι : Type*} [DecidableEq ι]
    (s : Finset ι) (nodes : ι → K) (hnodes : Set.InjOn nodes s) (y : ι → K) :
    ∃ p : Polynomial K, ∀ i ∈ s, p.eval (nodes i) = y i :=
  ⟨Lagrange.interpolate s nodes y, fun _ hi => Lagrange.eval_interpolate_at_node y hnodes hi⟩

end SpectralSupport

section FieldAndDiagonalizabilityBoundaries

/-- The quarter-turn rotation of the real plane. -/
def planeRotation : Matrix (Fin 2) (Fin 2) ℝ := !![0, -1; 1, 0]

/-- The two-by-two Jordan block with the repeated eigenvalue two. -/
def jordanBlock : Matrix (Fin 2) (Fin 2) ℝ := !![2, 1; 0, 2]

/-- A real rotation has no real eigenvector: the splitting field matters. -/
theorem planeRotation_has_no_real_eigenvector (c : ℝ) (v : Fin 2 → ℝ)
    (h : planeRotation *ᵥ v = c • v) : v 0 = 0 ∧ v 1 = 0 := by
  have h0 := congrFun h 0
  have h1 := congrFun h 1
  simp [planeRotation, Matrix.mulVec, dotProduct, Fin.sum_univ_two] at h0 h1
  have hsq : (1 + c ^ 2) * v 1 = 0 := by linear_combination -h0 - c * h1
  have hv1 : v 1 = 0 := by
    rcases mul_eq_zero.mp hsq with hz | hz
    · nlinarith [sq_nonneg c]
    · exact hz
  exact ⟨by rw [h1, hv1, mul_zero], hv1⟩

/-- Every real eigenvector of the Jordan block lies on one line, so no real
eigenbasis exists and the matrix is not diagonalizable over the reals. -/
theorem jordanBlock_eigenvectors_lie_on_one_line (c : ℝ) (v : Fin 2 → ℝ)
    (h : jordanBlock *ᵥ v = c • v) : v 1 = 0 := by
  have h0 := congrFun h 0
  have h1 := congrFun h 1
  simp [jordanBlock, Matrix.mulVec, dotProduct, Fin.sum_univ_two] at h0 h1
  rcases h1 with hc | hv
  · rw [← hc] at h0
    linarith
  · exact hv

/-- Scalar values on the spectrum do not determine the polynomial action when an
eigenvalue repeats: the nilpotent part still carries derivative data. -/
theorem jordanBlock_action_needs_more_than_values :
    Polynomial.eval (2 : ℝ) Polynomial.X = Polynomial.eval (2 : ℝ) (Polynomial.C 2) ∧
      Polynomial.aeval jordanBlock (Polynomial.X : Polynomial ℝ) ≠
        Polynomial.aeval jordanBlock (Polynomial.C 2 : Polynomial ℝ) := by
  refine ⟨by simp, ?_⟩
  intro hcontra
  have hentry := congrFun (congrFun hcontra 0) 1
  simp [jordanBlock, Matrix.algebraMap_matrix_apply] at hentry

end FieldAndDiagonalizabilityBoundaries

namespace Exercises.Chapter06

/-- CFT-06-E01. -/
theorem exercise_01_solution :
    (!![3, 0; 0, 5] : Matrix (Fin 2) (Fin 2) ℝ) *ᵥ ![1, 0] = (3 : ℝ) • ![1, 0] ∧
      (!![3, 0; 0, 5] : Matrix (Fin 2) (Fin 2) ℝ) *ᵥ ![0, 1] = (5 : ℝ) • ![0, 1] ∧
      ∀ v : Fin 2 → ℝ, (!![3, 0; 0, 5] : Matrix (Fin 2) (Fin 2) ℝ) *ᵥ v = (3 : ℝ) • v →
        v 1 = 0 := by
  refine ⟨?_, ?_, ?_⟩
  · ext i; fin_cases i <;> simp [Matrix.mulVec, dotProduct, Fin.sum_univ_two]
  · ext i; fin_cases i <;> simp [Matrix.mulVec, dotProduct, Fin.sum_univ_two]
  · intro v hv
    have h1 := congrFun hv 1
    simp [Matrix.mulVec, dotProduct, Fin.sum_univ_two] at h1
    linarith

/-- CFT-06-E02. -/
theorem exercise_02_solution :
    Polynomial.aeval jordanBlock ((Polynomial.X : Polynomial ℝ) ^ 3) = !![8, 12; 0, 8] ∧
      jordanBlock ^ 3 = !![8, 12; 0, 8] := by
  have hpow : jordanBlock ^ 3 = !![8, 12; 0, 8] := by
    simp [jordanBlock, pow_succ]
    norm_num
  refine ⟨?_, hpow⟩
  rw [map_pow, Polynomial.aeval_X, hpow]

/-- CFT-06-E03. -/
theorem exercise_03_solution {K m : Type*} [Field K] [Fintype m] [DecidableEq m]
    {A : Matrix m m K} {v : m → K} {c : K} (h : A *ᵥ v = c • v) (p : Polynomial K) :
    (Polynomial.aeval A p) *ᵥ v = (p.eval c) • v ∧
      (∀ k : ℕ, (A ^ k) *ᵥ v = c ^ k • v) ∧
      (p.eval c = 0 → (Polynomial.aeval A p) *ᵥ v = 0) := by
  refine ⟨aeval_mulVec_eigenvector h p, pow_mulVec_eigenvector h, ?_⟩
  intro hroot
  rw [aeval_mulVec_eigenvector h p, hroot, zero_smul]

/-- CFT-06-E04. -/
theorem exercise_04_solution {K m : Type*} [Field K] [Fintype m] [DecidableEq m]
    (S R : Matrix m m K) (d : m → K) (h : R * S = 1) (p : Polynomial K) :
    Polynomial.aeval (S * Matrix.diagonal d * R) p =
      S * Matrix.diagonal (fun i => p.eval (d i)) * R := by
  rw [conjugate_aeval h p, aeval_diagonal]

/-- CFT-06-E05. -/
theorem exercise_05_solution :
    Polynomial.eval (2 : ℝ) Polynomial.X = Polynomial.eval (2 : ℝ) (Polynomial.C 2) ∧
      Polynomial.aeval jordanBlock (Polynomial.X : Polynomial ℝ) ≠
        Polynomial.aeval jordanBlock (Polynomial.C 2 : Polynomial ℝ) ∧
      Polynomial.aeval jordanBlock
          ((Polynomial.X : Polynomial ℝ) - Polynomial.C 2) = !![0, 1; 0, 0] ∧
      ∀ c : ℝ, ∀ v : Fin 2 → ℝ, jordanBlock *ᵥ v = c • v → v 1 = 0 := by
  refine ⟨jordanBlock_action_needs_more_than_values.1,
    jordanBlock_action_needs_more_than_values.2, ?_,
    fun c v h => jordanBlock_eigenvectors_lie_on_one_line c v h⟩
  rw [map_sub, Polynomial.aeval_X, Polynomial.aeval_C]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [jordanBlock, Matrix.algebraMap_matrix_apply]

/-- CFT-06-E06. -/
theorem exercise_06_solution (A : SquareMatrix (Fin 2)) {ε : ℝ} (hε : 0 < ε) :
    ∃ B : SquareMatrix (Fin 2), HasDistinctEigenvalues B ∧ ‖B - A‖ < ε :=
  exists_hasDistinctEigenvalues_norm_sub_lt A hε

end Exercises.Chapter06

end CrouzeixTextbook.Part01

#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_01_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_02_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_03_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_04_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_05_solution
#check CrouzeixTextbook.Part01.Exercises.Chapter06.exercise_06_solution
