import CrouzeixConjecture.GeneratedAlgebra
import CrouzeixConjecture.SimpleSpectrumBridge
import CrouzeixConjecture.SimpleSpectrumDensity
import CrouzeixConjecture.Spectrum

namespace CrouzeixTextbook.Part01

open CrouzeixConjecture
open scoped Matrix.Norms.L2Operator

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- CFT-06-001: polynomial action on a diagonal matrix is entrywise evaluation. -/
def polynomial_action_diagonal := @polynomialEval_diagonal

/-- CFT-06-002: polynomial action preserves an explicitly supplied eigenbasis. -/
def diagonalizable_polynomial_calculus := @SimpleDiagonalization.polynomialEval_eq_innerConjugation_diagonal

/-- CFT-06-003: every supplied eigenvalue belongs to the spectrum. -/
def diagonalization_eigenvalue_mem_spectrum := @SimpleDiagonalization.eigenvalue_mem_matrixSpectrum

/-- CFT-06-004: every polynomial action lies in the algebra generated by the matrix. -/
def polynomial_action_mem_generated_algebra := @polynomialEval_mem_generatedAlgebra

/-- CFT-06-005: the singly generated algebra consists exactly of polynomial actions. -/
def generated_algebra_polynomial_representation := @generatedAlgebra_mem_iff_exists_polynomial

/-- CFT-06-006: simple-spectrum matrices are dense in finite complex matrix space. -/
def simple_spectrum_dense := @exists_hasDistinctEigenvalues_norm_sub_lt

end CrouzeixTextbook.Part01
